[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
[project]
name = "getDatesPackage"
version = "0.0.1"
authors = [
  { name="Bill Weatherwax", email="waxcruz@yahoo.com" },
]
description = "Generate dates from a start date to end date"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/waxcruz/GetDates.git" 
"Bug Tracker" = "https://github.com/waxcruz/GetDates.git/issues"